### ISSUE TITLE
xenorchestra.com - e-mail confirmation link doesn't set account to 'confirmed'

### ISSUE THREAD

**Issue by camilosantana** [esotalk/esoTalk#178] opened 2014-04-10 23:05 UTC
following the 'report a bug' link. i get the confirmation e-mail. when i click it, i get redirected to the site. i attempt to login. i get notified that i need to confirm my e-mail address. infinite workflow loop ensues.

**Comment by tvb** [comment] 2014-04-11 06:39
This is caused by this bug https://github.com/tristanvanbokkem/esoTalk/commit/f836535cddbdf8d6d03d7e26bd509bba33f97901

**Comment by tobyzerner** [comment] 2014-04-12 05:24
Fixed in cb4c201

**Closed as completed by tobyzerner** 2014-04-12 05:24 UTC
