### ISSUE TITLE
Avatars in threads, is something fishy?

### ISSUE THREAD

**Issue by henhouse** [esotalk/esoTalk#5] opened 2011-11-14 06:21 UTC
I was noticing how avatars like to appear and disappear when deleting posts, restoring posts, and reloading the page altogether.

Here's some screenshots I've compiled:

Deleted posted both avatars disappeared:
http://i42.tinypic.com/2rxxwz9.png

Restored, still gone:
http://i41.tinypic.com/rw79ci.png

Also, all avatars will bunch after double/triple, etc posting: (is it intentional?)
http://i40.tinypic.com/2ptqjde.png

But on reload... (intentional?)
http://i39.tinypic.com/2luouu9.png

**Comment by tobyzerner** [comment] 2011-11-15 06:06
Having a single avatar per consecutive posts by the same member is intended behaviour. The third screenshot you posted shows incorrect behaviour, which should be fixed.

**Closed as completed** 2012-01-19 09:10 UTC
Labels: Bug
