### ISSUE TITLE
Date format in Timeline

### ISSUE THREAD

**Issue by TomaszGasior** [esotalk/esoTalk#57] opened 2012-01-31 17:10 UTC
I write polish language for esoTalk, but I don't good speak in English, so I'm sorry for my errors. :)

In Polish other date format is in Timeline and other date format is in post date.
For example: January in Polish in Timeline is "Styczen" and in post date is "stycznia".
So, please of feature edit date (month) format in Timeline in language file.

**Comment by tobyzerner** [comment] 2013-02-09 08:38
Duplicate of #50

**Closed as completed by tobyzerner** 2013-02-09 08:38 UTC
