### ISSUE TITLE
member?name=Toby , Page Not Found

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#19] opened 2011-11-14 08:52 UTC
member?name=iugo , Page Not Found too.

**Comment by jgknight** [comment] 2011-11-14 16:18
Can you give an example URL that link can be found on?  I can't seem to find any profile links that go to a 404 page.

**Comment by iugo** [comment] 2011-11-15 01:25
http://esotalk.org/forum/member?name=iugo
http://esotalk.org/forum/member?name=Toby

URLs in "quote"

**Comment by jgknight** [comment] 2011-11-15 02:45
This is a duplicate of bug esotalk/esoTalk#3

**Closed as completed by jgknight** 2011-11-15 02:45 UTC
