### ISSUE TITLE
 jump page error after login.

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#47] opened 2011-11-21 07:10 UTC
URL is " http://jztk.tk/index.php/http://jztk.tk/ " after I login.

http://jztk.tk/
username:test
password:111111

**Comment by iugo** [comment] 2011-11-21 07:25
Issue #6 
https://github.com/esotalk/esoTalk/issues/6

**Comment by tobyzerner** [comment] 2012-01-19 08:34
Duplicate of #6

**Closed as completed by tobyzerner** 2012-01-19 08:34 UTC
