### ISSUE TITLE
Fatal error when linking to unknown member profile

### ISSUE THREAD

**Issue by alexcroox** [esotalk/esoTalk#329] opened 2014-08-16 03:00 UTC
I was experimenting with the custom profile fields plugin and didn't know what the member reference field did. So I enabled it and typed in some junk. It produced a link to:

http://localhost/esotalk/member/name/fewfw

however this produced the following error when followed:

`Fatal error: Call to undefined method ETMemberController::index() in esotalk/core/controllers/ETMemberController.class.php on line 56`

If I manually change the URL to a name that definitely exists it correctly redirects to /member/1-username

**Comment by tobyzerner** [comment] 2014-08-16 05:14
Duplicate of #307, fixed in 4cce7be9fd5de19589b5cc8ffa5655df9d28c0a2

**Closed as completed by tobyzerner** 2014-08-16 05:14 UTC
