### ISSUE TITLE
Search doesn't work in native language

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#287] opened 2014-06-03 23:56 UTC
Hi!

I have a problem with search - when conversation is in Russian, it doesn't work... when in English it's all ok.

Have no idea what may cause this, can anyone please advice? I have a test installation on my Windows PC, Running OpenServer (WAMP-like) including:

```
Apache-2.4.9
PHP-5.5.10
MySQL-5.6.17
```

I have also made few shots, please take a look in attachment...

![1](https://cloud.githubusercontent.com/assets/6797881/3168142/b0fb2e98-eb7a-11e3-9624-bad456387def.png)
![2](https://cloud.githubusercontent.com/assets/6797881/3168141/b0fadb96-eb7a-11e3-9e19-547ec70f1308.png)
![3](https://cloud.githubusercontent.com/assets/6797881/3168143/b0fc5f16-eb7a-11e3-8456-48561f98d8c3.png)

**Comment by tobyzerner** [comment] 2014-08-01 05:19
Closing this because with my tests, I've not been able to reproduce.

Could you please post the exact text of your post where search is not working for you?

**Closed as completed by tobyzerner** 2014-08-01 05:19 UTC

**Comment by inliquid** [comment] 2014-08-01 12:35
It doesn't work only on Windows as I said in the opening post. Any Russian text, doesn't matter, as an example: "утюги".

**Comment by tobyzerner** [comment] 2014-08-02 00:58
Right, so it's probably a Windows MySQL issue? Unless you can give evidence that something's wrong in the esoTalk codebase.
