### ISSUE TITLE
users cant create an account

### ISSUE THREAD

**Issue by jevo99** [esotalk/esoTalk#333] opened 2014-08-22 20:36 UTC
when a user try's to sign up for my forum it freezes and looks like the webpage is trying to load for around 5 minutes before cloud-flair kicks in and says the site is offline even though the web server is still running perfectly well.

thanks for your support,
josh.

**Comment by dutok** [comment] 2014-08-23 04:12
This sounds like a MySQL problem.

**Comment by dutok** [comment] 2014-08-23 04:15
Also, can you post the error from the your apache/nginx error log?

**Comment by jevo99** [comment] 2014-08-23 21:10
It seems to be an issue with the confirmation email sending service as if I enable the SMTP plugin I get this error 
![img_0053](https://cloud.githubusercontent.com/assets/4163654/4021838/c29ddea6-2b09-11e4-8c99-11324ceb82c6.PNG)

And I will get the error logs to you ASAP as I'm not able to access them at the minute.

**Comment by tobyzerner** [comment] 2014-08-24 01:00
http://esotalk.org/docs/debug

**Comment by jgknight** [comment] 2015-01-31 17:05
I'm closing this as it's not an issue with esoTalk code. If you need help please checkout the support forum. Once it's determined to be an actual bug, we can open an issue here for the specific root cause.

**Closed as completed by jgknight** 2015-01-31 17:05 UTC
