### ISSUE TITLE
New conversations in Safari 5.0.5 don't work

### ISSUE THREAD

**Issue by ghost** [esotalk/esoTalk#35] opened 2011-11-14 20:23 UTC
using safari Version 5.0.5 (6533.21.1) here and I can't start a new conversation, just tested firefox on the same machine and it works perfectly. Also Thank you so much esotalk rules!

**Comment by tobyzerner** [comment] 2012-01-19 04:21
Cannot reproduce, closing.

**Closed as completed by tobyzerner** 2012-01-19 04:21 UTC
Labels: Bug

**Comment by iugo** [comment] 2012-07-15 03:55
I encountered a similar problem.
iPod touch (4g), iOS 4.3.3

New conversations in Safari 5.0.5 don't work
When I created a new conversation, blank pages except the title bar.
